apiVersion: v2
appVersion: '1.0'
description: A Helm chart for pip-frontend App
name: pip-frontend
home: https://github.com/hmcts/pip-frontend
version: 0.0.51
maintainers:
    - name: HMCTS PIP Team
dependencies:
    - name: nodejs
      version: 2.4.18
      repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
