apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Publishing-information-project-PI App
name: Publishing-information-project-PI
home: https://github.com/hmcts/pip-frontend
version: 0.0.1
maintainers:
  - name: HMCTS PIP Team
dependencies:
  - name: nodejs
    version: 2.3.4
    repository: '@hmctspublic'

